# Generated by Django 3.2.7 on 2026-01-05 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_camera_dumpingevent_numberplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpingevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.legaldumpinglocation'),
        ),
    ]
