# Generated by Django 3.2.7 on 2026-01-08 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_garbageevidence_garbagereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbagereport',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='garbagereport',
            name='severity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='garbagereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='login.normal_user'),
        ),
    ]
